const fs = require('fs');
if (fs.existsSync('config.env')) require('dotenv').config({ path: './config.env' });

module.exports = {
  "SESSION_ID": process.env.SESSION_ID || "Byte;;;eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoibUp2V1l6UjczVzBIdlY5NzhubkwrSVZub0hvNkNCczB2dWphb2JRMnkyWT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiRkJNa2duQXVNaUJGR0g0ZE92bk1hQTVQZTQ5K3NkZVByV1pjSEZkc1VXQT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJFRExsb2VXbktpZ1JZYWtXbkd0ZzltOU1aZlhWYnRCNWl4WkZqcVBieWtnPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJkeFE3RFd0YTVwTXo3U2JreE54aERTUzk1V0oyZlZ2eGhHTGhYNmJ1ZmgwPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjBNeTJlTnB2eHFac2hxSUo4THh6MGt4dHRWSEtDT1U0bHozbFFGclNHRmM9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlMyRWxtVUltVjRVblppQUVkdVFWeldFR1RYSWFZRVdLWUdCek85VjlJVEE9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiaUtPUzMyVVBib1dvYTBTd3FYNmxCdUE5QnFiZzhrUEdCNG5wVDgvTDZrYz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiRUIySzRUdWFtbG5uVXJ1bGdNQWw0VHBoM2c3Z0ZmaFpjZC9kMWx0SHVDWT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik9XcUx2MHNtd0ZhYU1Dcit0UzkyajNwRUErRSsvZm1ZWVpHREI2eUp5UHQ5K01sZUc2SkRiRDRNWEdYWGhuNG1QbEN3YkNyekdJQXg5N09WK2hYUGlnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTAxLCJhZHZTZWNyZXRLZXkiOiJMTDFqL0xHMGlZTE9XYzZ1TUZyaGVjRktKMHJ6N0R1UUpOcDNNSDhxbmNrPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6IjI1NDc0MjM3ODUxMUBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiI3NzVCRTI1MzJENjFBNjg4NDlDNTYyOEM1RjkwQ0M5QSJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzM1OTM0MDg0fSx7ImtleSI6eyJyZW1vdGVKaWQiOiIyNTQ3NDIzNzg1MTFAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiQjQ0MjYyMUI2MkExM0VBQkY4N0IwMzZFQjdEMzNDNzYifSwibWVzc2FnZVRpbWVzdGFtcCI6MTczNTkzNDA4NH1dLCJuZXh0UHJlS2V5SWQiOjMxLCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZCI6MzEsImFjY291bnRTeW5jQ291bnRlciI6MSwiYWNjb3VudFNldHRpbmdzIjp7InVuYXJjaGl2ZUNoYXRzIjpmYWxzZX0sImRldmljZUlkIjoiNVU0RTVNd3pRTC03SHo4bXN0enIxQSIsInBob25lSWQiOiI1YjcwOWIwNy0wNjY3LTQ3Y2UtYjEwNC1kYTlhMWU0YmU0ZDYiLCJpZGVudGl0eUlkIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiRXNjc3NkYVB2Z21Wd0tDWDBTSGo5SElPeUljPSJ9LCJyZWdpc3RlcmVkIjp0cnVlLCJiYWNrdXBUb2tlbiI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik9CZ0JaRURtR25EakRxT0lpdDd0SzBxWG5DMD0ifSwicmVnaXN0cmF0aW9uIjp7fSwicGFpcmluZ0NvZGUiOiJZN0JNQ1Y2RCIsIm1lIjp7ImlkIjoiMjU0NzQyMzc4NTExOjIxQHMud2hhdHNhcHAubmV0IiwibmFtZSI6ImVubm94ePCfkb0ifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ09QQXg5RURFTytBNGJzR0dCQWdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6IlA5emIzanE4N2Vmdi9aUi9uT3oxbnhwVzR2OWhBdkdEQi9mdjRvTGhjQTg9IiwiYWNjb3VudFNpZ25hdHVyZSI6IjdmOXNVaVNMMjFiaHFsSFdmVUVSZWZERUZCMHVGaWFYN29VSHNIcDFjeDNpWmpWS1FnRWZKV2tJZW9VeDA5NXoxODIyK0dpTDlGbG5QaXFTWC9ZOUNnPT0iLCJkZXZpY2VTaWduYXR1cmUiOiJXcXZwNnp6SGx4bkR0aHU0QnFNdnBWcHdycXFEWjk2N3VTZUhKYnRJQzFVV2lROTlkZG9wcnpiQkU5NnBJSlVKakQ0NlpMWmRsNmNJb3J5OHNBdDNpZz09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjI1NDc0MjM3ODUxMToyMUBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJUL2MyOTQ2dk8zbjcvMlVmNXpzOVo4YVZ1TC9ZUUx4Z3dmMzcrS0M0WEFQIn19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzM1OTM0MDc3LCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQUlaaSJ9",
  "ALIVE_IMG": process.env.ALIVE_IMG || "https://raw.githubusercontent.com/HyHamza/HyHamza/refs/heads/main/Images/logo.jpg",
  "PREFIX": process.env.PREFIX || ".",
  "AUTO_READ_STATUS": process.env.AUTO_READ_STATUS === 'true',
  "MODE": process.env.MODE || "public",
  "OWNER_NUMBER": process.env.OWNER_NUMBER || "923072380380",
  "OWNER_NAME": process.env.OWNER_NAME || "Hamza",
  "ALWAYS_ONLINE": process.env.ALWAYS_ONLINE === 'true',
  "PRESENCE": process.env.PRESENCE || "online",
  "OMDB_API_KEY": process.env.OMDB_API_KEY || "76cb7f39",
  "READ_CMD": process.env.READ_CMD === 'true',
  "AUTO_VOICE": process.env.AUTO_VOICE === 'true',
  "AUTO_STICKER": process.env.AUTO_STICKER === 'true',
  "AUTO_REPLY": process.env.AUTO_REPLY === 'true',
  "AUTO_REACT": process.env.AUTO_REACT === 'true',
  "WELCOME": process.env.WELCOME === 'true',
  "ANTI_BAD": process.env.ANTI_BAD === 'true',
  "ANTI_LINK": process.env.ANTI_LINK === 'true',
  "ANTI_GROUP_LINK": process.env.ANTI_GROUP_LINK === 'true',
  "ANTI_DELETE": process.env.ANTI_DELETE === 'true',
  "ANTI_VIEW_ONCE": process.env.ANTI_VIEW_ONCE === 'true',
  "ANTI_BOT": process.env.ANTI_BOT === 'true',
  "PREMIUM_USERS": process.env.PREMIUM_USERS || "",
  "COUNTRY_BLOCK": process.env.COUNTRY_BLOCK === 'true',
  "COUNTRY_BLOCK_CODE": process.env.COUNTRY_BLOCK_CODE || "972",
  "EMOJI": process.env.EMOJI || "🙄",
  "AUTO_TYPING": process.env.AUTO_TYPING === 'true'
};
